services:
    surfnet_gateway_api.service.sms:
        class: Surfnet\StepupGateway\ApiBundle\Service\SmsService
        arguments:
            - @surfnet_message_bird_api_client.messaging
            - @logger

    surfnet_gateway_api.service.yubikey:
        class: Surfnet\StepupGateway\ApiBundle\Service\YubikeyService
        arguments:
            - @surfnet_yubikey_api_client.verification_service
            - @logger

    surfnet_gateway_api.listener.json_response_http_exception:
        class: Surfnet\StepupGateway\ApiBundle\EventListener\JsonResponseHttpErrorListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
