services:
    surfnet_gateway_api.service.sms:
        class: Surfnet\StepupGateway\ApiBundle\Service\SmsService
        arguments:
            - @surfnet_message_bird_api_client.messaging
            - @logger

    surfnet_gateway_api.service.yubikey:
        class: Surfnet\StepupGateway\ApiBundle\Service\YubikeyService
        arguments:
            - @surfnet_yubikey_api_client.verification_service
            - @logger

    surfnet_gateway_api.security.json_basic_auth_entry_point:
        class: Surfnet\StepupGateway\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - ~ # HTTP Basic realm string, see extension

    surfnet_gateway_api.service.u2f_verification:
        class: Surfnet\StepupGateway\ApiBundle\Service\U2fVerificationService
        arguments:
            - @surfnet_stepup_u2f_verification.service.u2f_verification
            - @logger
