services:
    surfnet_gateway_api.service.sms:
        class: Surfnet\StepupGateway\ApiBundle\Service\SmsService
        arguments:
            - @surfnet_message_bird_api_client.messaging
            - @logger
