surfnet_saml_metadata:
    path:     /metadata
    methods:  [GET]
    defaults: { _controller: SurfnetSamlBundle:Metadata:metadata}

# Disabled for now, as it is not yet known how the param -> idp is generated
#surfnet_saml_metadata_identityprovider_proxy:
#    path:     /metadata/{idp}
#    methods:  [GET]
#    defaults: { _controller: SurfnetSamlBundle:Metadata:proxyMetadata }

surfnet_saml_serviceprovider_consume_assertion:
    path:     /consume-assertion
    methods:  [POST]
    defaults: { _controller: SurfnetSamlBundle:ServiceProvider:consumeAssertion }

surfnet_saml_identityprovider_sso:
    path:     /single-sign-on
    methods:  [POST]
    defaults: { _controller: SurfnetSamlBundle:IdentityProvider:ssoAssertion }
