services:
    surfnet_saml.metadata_factory:
        class: Surfnet\SamlBundle\Metadata\MetadataFactory
        arguments:
            - @templating
            - @router
            - @surfnet_saml.signing_service

    surfnet_saml.signing_service:
        class: Surfnet\SamlBundle\Service\SigningService
        arguments:
            - @surfnet_saml.saml2.keyloader
            - @surfnet_saml.saml2.privatekeyloader

    surfnet_saml.saml2.keyloader:
        public: false
        class: SAML2_Certificate_KeyLoader

    surfnet_saml.saml2.privatekeyloader:
        public: false
        class: SAML2_Certificate_PrivateKeyLoader

