# try to create a dependabot to monitor updates on the monitor bundle
version: 2
updates:
  - package-ecosystem: "composer" # Your package manager
    directory: "/" # The directory where your `composer.json` file is
    schedule:
      interval: "daily" # Check for updates daily
    target-branch: "main" # The branch to create the pull request against
    allow:
      - dependency-name: "openconext/monitor-bundle" # Replace with the name of the package
