---
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directories:
      - "/docker/"
    schedule:
      interval: "daily"
    groups:
      docker:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      javascript-prod:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      javascript-dev:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - "minor"
          - "patch"
  # Maintain dependencies for npm
  - package-ecosystem: "composer"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "symfony/*"
    groups:
      php-prod:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      php-dev:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - "minor"
          - "patch"
