
jms_translation:
  locales: "%locales%"
  configs:
    default:
      dirs: ["%kernel.project_dir%/src", "%kernel.project_dir%/templates", "%kernel.project_dir%/vendor/surfnet"]
      output_dir: "%kernel.project_dir%/translations"
      ignored_domains: []
      excluded_names:
        - '*TestCase.php'
        - '*Test.php'
        - 'Assert.php'
        - 'RegistrationExpirationHelper.php'
        - 'SecondFactorTypeTranslationService.php'
      excluded_dirs: [cache, data, logs, Tests]
      extractors: []
