
jms_translation:
  locales: "%locales%"
  configs:
    default:
      dirs: ["%kernel.root_dir%/../src", "%kernel.root_dir%", "%kernel.root_dir%/../vendor/surfnet"]
      output_dir: "%kernel.root_dir%/translations"
      ignored_domains: []
      excluded_names:
        - '*TestCase.php'
        - '*Test.php'
        - 'Assert.php'
        - 'RegistrationExpirationHelper.php'
        - 'SecondFactorTypeTranslationService.php'
      excluded_dirs: [cache, data, logs, Tests]
      extractors: []
