monolog:
  channels: [ authentication ]

  handlers:
    prod-signaler:
      type: fingers_crossed
      action_level: ERROR
      passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
      handler: main_syslog
      bubble: false # if we handle it, nothing else should
    main_syslog:
      type: stream
      path: "php://stderr"
      formatter: surfnet_stepup.monolog.json_formatter

when@dev: &override
  monolog:
    handlers:
      main_syslog:
        type: stream
        path: php://stderr
        level: error
        channels: ["!event", "!doctrine", "!deprecation", "!console"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!deprecation", "!console"]
when@test: *override
when@smoketest: *override
