surfnet_stepup_gateway_gateway:
  intrinsic_loa: "%gateway_loa_loa1%"
  enabled_second_factors: "%enabled_second_factors%"
  enabled_generic_second_factors: "%enabled_generic_second_factors%"
  sso_on_second_factor:
    cookie_type: "%sso_cookie_type%"
    cookie_name: "%sso_cookie_name%"
    cookie_lifetime: "%sso_cookie_lifetime%"
    encryption_key: "%sso_encryption_key%"

surfnet_stepup_gateway_second_factor_only:
  loa_aliases:
    - loa: "%gateway_loa_loa2%"
      alias: "%second_factor_only_loa_loa2%"
    - loa: "%gateway_loa_loa3%"
      alias: "%second_factor_only_loa_loa3%"
    - loa: "%gateway_loa_self_asserted%"
      alias: "%second_factor_only_loa_self_asserted%"
    - loa: 'http://stepup.example.com/assurance/loa-3'
      alias: "%second_factor_only_loa_loa3%"
