surfnet_stepup_gateway_gateway:
  intrinsic_loa: "%gateway_loa_loa1%"
  enabled_second_factors: "%enabled_second_factors%"
  enabled_generic_second_factors: "%enabled_generic_second_factors%"

surfnet_stepup_gateway_second_factor_only:
  loa_aliases:
    - loa: "%gateway_loa_loa2%"
      alias: "%second_factor_only_loa_loa2%"
    - loa: "%gateway_loa_loa3%"
      alias: "%second_factor_only_loa_loa3%"
    - loa: "%gateway_loa_self_asserted%"
      alias: "%second_factor_only_loa_self_asserted%"
    - loa: 'http://stepup.example.com/assurance/loa-3'
      alias: "%second_factor_only_loa_loa3%"
