imports:
    - { resource: config.yml }

# Be careful not to remove the prod-signaler handler, which overwrites
# the prod-signaler handler defined in logging.yml. The handler defined
# in logging.yml disables bubbling which means that none of the handlers
# below are invoked. Since the current dev setup is incompatible with the
# prod setup defined in logging.yml, this means we won't see any logs in
# the infrastructure currently used (graylog). Overwriting the handler
# here resolves that and reinstates the dev logging setup.
#
# this configuration must be replaced to reflect production setup
# see https://www.pivotaltracker.com/story/show/96056010
#
monolog:
    channels: [authentication]
    handlers:
        prod-signaler:
            type: group
            members:
                - main_syslog
            bubble: false # if we handle it, nothing else should
            channels: ["!authentication"] # the auth channel is logged by the next handler
        main_syslog:
            type: syslog
            ident: stepup-gateway
            facility: user
            level: DEBUG
            formatter: surfnet_stepup.monolog.json_formatter
        authenthentication_syslog:
            type: syslog
            ident: stepup-authentication
            facility: user
            level: INFO
            channels: [authentication]
            formatter: gateway.monolog.gelf_to_string_formatter

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

assetic:
    use_controller: "%use_assetic_controller%"

nelmio_security:
    csp:
        img: [ self, 'data:' ]
        script: [ self, unsafe-inline ]
        style: [ self, unsafe-inline ]
        report_only: true
