imports:
    - { resource: config_prod.yml }

doctrine:
    orm:
        # This disables Doctrine proxy cache warming, which requires the database. When the cache is warmed on
        # production, the classes will be generated.
        auto_generate_proxy_classes: true
