imports:
    - { resource: config.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

nelmio_security:
    csp:
        img: [ self, 'data:' ]
        script: [ self, unsafe-inline ]
        style: [ self, unsafe-inline ]

doctrine:
    dbal:
        default_connection: gateway
        connections:
            gateway:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_gateway_name%_test"
                user:     "%database_gateway_user%"
                password: "%database_gateway_password%"
                charset:  UTF8
            u2f:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_u2f_name%_test"
                user:     "%database_u2f_user%"
                password: "%database_u2f_password%"
                charset:  UTF8
            deploy:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_u2f_name%_test"
                user:     "%database_deploy_user%"
                password: "%database_deploy_password%"
                charset:  UTF8

