imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

nelmio_security:
    csp:
        img: [ self, 'data:' ]
        script: [ self, unsafe-inline ]
        style: [ self, unsafe-inline ]
