imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:        sess_gateway
        cookie_httponly: true
        cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle, SurfnetStepupGatewayApiBundle]
    #java: /usr/bin/java
    node: "/usr/bin/node"
    node_paths: ["/usr/lib/node_modules"]
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: gateway
        connections:
            gateway:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_gateway_user%"
                password: "%database_gateway_password%"
                charset:  UTF8
            deploy:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_deploy_user%"
                password: "%database_deploy_password%"
                charset:  UTF8
    orm:
        default_entity_manager: gateway
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            gateway:
                connection: gateway
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings: []
            deploy:
                connection: deploy
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings: []

doctrine_migrations:
    namespace: Surfnet\StepupGateway\Migrations
    table_name: migration_versions
    name: Step-up Gateway Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_security:
    # Content Security Policy
    csp:
        report_uri: /csp/report
        # Log to security channel
        report_logger_service: monolog.logger.security
        # Content types: default, script, object, style, img, media, frame, font, connect
        default: [ self ]
    signed_cookie:
        names: ['*']
    encrypted_cookie:
        names: ['*']

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

surfnet_message_bird_api_client:
    authorization: %messagebird_authorization%

surfnet_yubikey_api_client:
    credentials:
        client_id: %yubikey_client_id%
        client_secret: %yubikey_client_secret%

surfnet_stepup:
    logging:
        application_name: gw

monolog:
    handlers:
        graylog2:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler: graylog2_gelf

        graylog2_gelf: # Nested into graylog2
            type: gelf
            publisher: { hostname: g2-dev.stepup.coin.surf.net }
            formatter: surfnet_stepup.monolog.full_message_exception_gelf_message_formatter

surfnet_saml:
    entity_repository: saml.entity_repository
    hosted:
        service_provider:
            enabled: true
            assertion_consumer_route: gateway_serviceprovider_consume_assertion
            public_key: %saml_sp_publickey%
            private_key: %saml_sp_privatekey%
        identity_provider:
            enabled: true
            sso_route: gateway_identityprovider_sso
            public_key: %saml_idp_publickey%
            private_key: %saml_idp_privatekey%
        metadata:
            entity_id_route: gateway_saml_metadata
            public_key: %saml_metadata_publickey%
            private_key: %saml_metadata_privatekey%
    remote:
        identity_provider:
            enabled: true
            entity_id: %saml_remote_idp_entity_id%
            sso_url: %saml_remote_idp_sso_url%
            certificate: %saml_remote_idp_certificate%
