imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: samlstepupproviders.yml }
    - { resource: logging.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: %asset_version%
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: "%trusted_proxies%"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:        sess_gateway
        cookie_httponly: true
        cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:  SurfnetStepupBundle:Exception:show

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
     - MopaBootstrapBundle
     - SurfnetStepupGatewayApiBundle
     - SurfnetStepupGatewayGatewayBundle
     - SurfnetStepupGatewaySamlStepupProviderBundle
    #java: /usr/bin/java
    node: "/usr/bin/node"
    node_paths: ["/usr/lib/node_modules"]
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: gateway
        connections:
            gateway:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_gateway_name%"
                user:     "%database_gateway_user%"
                password: "%database_gateway_password%"
                charset:  UTF8
            u2f:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_u2f_name%"
                user:     "%database_u2f_user%"
                password: "%database_u2f_password%"
                charset:  UTF8
            deploy:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_u2f_name%"
                user:     "%database_deploy_user%"
                password: "%database_deploy_password%"
                charset:  UTF8
        types:
            u2f_key_handle: Surfnet\StepupGateway\U2fVerificationBundle\Doctrine\Type\KeyHandleType
            u2f_public_key:  Surfnet\StepupGateway\U2fVerificationBundle\Doctrine\Type\PublicKeyType
    orm:
        default_entity_manager: gateway
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            gateway:
                connection: gateway
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    SurfnetStepupGatewayGatewayBundle:
                        mapping: true
                        type: annotation
                        is_bundle: true
            u2f:
                connection: u2f
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    SurfnetStepupGatewayU2fVerificationBundle:
                        mapping: true
                        type: annotation
                        is_bundle: true
            deploy:
                connection: deploy
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings: []

doctrine_migrations:
    namespace: Surfnet\StepupGateway\Migrations
    table_name: migration_versions
    name: Step-up Gateway Migrations

nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    # Content Security Policy
    csp:
        report_uri: /csp/report
        # Log to security channel
        report_logger_service: monolog.logger.security
        # Content types: default, script, object, style, img, media, frame, font, connect
        default: [ self ]

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

mopa_bootstrap:
    form:
        show_legend: false
        templating: SurfnetStepupGatewayGatewayBundle:Form:fields.html.twig
    icons:
        icon_set: fontawesome4

surfnet_message_bird_api_client:
    authorization: %messagebird_authorization%

surfnet_yubikey_api_client:
    credentials:
        client_id: %yubikey_client_id%
        client_secret: %yubikey_client_secret%

surfnet_stepup:
    logging:
        application_name: stepup-gateway
    loa_definition:
        loa1: %gateway_loa_loa1%
        loa2: %gateway_loa_loa2%
        loa3: %gateway_loa_loa3%
    sms:
        service: gateway.service.gateway_api_sms
        originator: %sms_originator%
        otp_expiry_interval: %sms_otp_expiry_interval%
        maximum_otp_requests: %sms_maximum_otp_requests%
    locale_cookie:
        domain: %locale_cookie_domain%

surfnet_stepup_gateway_gateway:
    intrinsic_loa: %gateway_loa_loa1%
    enabled_second_factors: %enabled_second_factors%
    enabled_generic_second_factors: %enabled_generic_second_factors%

    # Policy Decision Point
    pdp:
        url: %pdp_url%
        username: %pdp_username%
        password: %pdp_password%
        client_id: %pdp_client_id%

surfnet_stepup_gateway_second_factor_only:
    loa_aliases:
        - loa: %gateway_loa_loa2%
          alias: %second_factor_only_loa_loa2%
        - loa: %gateway_loa_loa3%
          alias: %second_factor_only_loa_loa3%

surfnet_saml:
    hosted:
        service_provider:
            enabled: true
            assertion_consumer_route: gateway_serviceprovider_consume_assertion
            public_key: %saml_sp_publickey%
            private_key: %saml_sp_privatekey%
        identity_provider:
            enabled: true
            service_provider_repository: gateway.entity_service
            sso_route: gateway_identityprovider_sso
            public_key: %saml_idp_publickey%
            private_key: %saml_idp_privatekey%
        metadata:
            entity_id_route: gateway_saml_metadata
            public_key: %saml_metadata_publickey%
            private_key: %saml_metadata_privatekey%
    remote:
        identity_provider:
            enabled: true
            entity_id: %saml_remote_idp_entity_id%
            sso_url: %saml_remote_idp_sso_url%
            certificate: %saml_remote_idp_certificate%

jms_translation:
    locales: %locales%
    configs:
        default:
            dirs: [%kernel.root_dir%/../src, %kernel.root_dir%]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: []
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs, Tests]
            extractors: []

surfnet_stepup_u2f:
    app_id: %u2f_app_id%

surfnet_stepup_gateway_u2f_verification:
    migrations:
        diff_entity_manager: u2f
        migrate_entity_manager: deploy
