monolog:
    channels: [authentication]
    handlers:
        main:
            type: group
            members:
                - main_graylog
                - main_logfile
        main_graylog:
            type: buffer
            handler: graylog
            level: NOTICE
        main_logfile:
            type: stream
            handler: logfile
            level: NOTICE
            path: %kernel.logs_dir%/%kernel.environment%.log
        graylog:
            type: gelf
            publisher: { hostname: %graylog_hostname% }
            formatter: surfnet_stepup.monolog.full_message_exception_gelf_message_formatter
        authentication:
            type: stream
            handler: logfile
            level: INFO
            path: %kernel.logs_dir%/%kernel.environment%_authentication.log
            channels: [authentication]
            formatter: gateway.monolog.gelf_to_string_formatter
