monolog:
    channels: [authentication]
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: false # if we handle it, nothing else should
            channels: ["!authentication"] # the auth channel is logged by the next handler
        main_syslog:
            type: syslog
            ident: stepup-gateway
            facility: user
            formatter: surfnet_stepup.monolog.json_formatter
        authenthentication_syslog:
            type: syslog
            ident: stepup-authentication
            facility: user
            level: INFO
            channels: [authentication]
            formatter: surfnet_stepup.monolog.json_formatter
