surfnet_saml:
    resource: "@SurfnetSamlBundle/Resources/config/routing.yml"
    prefix:   /authentication

nelmio_security_report:
    path: /csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods: [POST]

surf_stepup:
    resource: @SurfnetStepupGatewayApiBundle/Resources/config/routing.yml
    prefix: /api
