surfnet_stepup_gateway_saml_stepup_provider:
    resource: "@SurfnetStepupGatewaySamlStepupProviderBundle/Resources/config/routing.yml"
    prefix:   /

surfnet_stepup_gateway_gateway:
    resource: "@SurfnetStepupGatewayGatewayBundle/Resources/config/routing.yml"
    prefix:   /

surfnet_stepup_gateway_second_factor_only:
    resource: "@SurfnetStepupGatewaySecondFactorOnlyBundle/Resources/config/routing.yml"
    prefix:   /

openconext_monitor:
    resource: "@OpenConextMonitorBundle/Resources/config/routing.yml"
    prefix: /

nelmio_security_report:
    path: /csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods: [POST]

surf_stepup:
    resource: @SurfnetStepupGatewayApiBundle/Resources/config/routing.yml
    prefix: /api
