imports:
    - { resource: samlstepupproviders_parameters.yml }

surfnet_stepup_gateway_saml_stepup_provider:
    allowed_sps: %gssp_tiqr_allowed_sps%
    routes:
        sso: %gssp_routes_sso%
        consume_assertion: %gssp_routes_consume_assertion%
        metadata: %gssp_routes_metadata%
    providers:
        tiqr:
            enabled: %gssp_tiqr_enabled%
            hosted:
                service_provider:
                    public_key: %gssp_tiqr_sp_publickey%
                    private_key: %gssp_tiqr_sp_privatekey%
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: %gssp_tiqr_idp_publickey%
                    private_key: %gssp_tiqr_idp_privatekey%
                metadata:
                    public_key: %gssp_tiqr_metadata_publickey%
                    private_key: %gssp_tiqr_metadata_privatekey%
            remote:
                entity_id: %gssp_tiqr_remote_entityid%
                sso_url: %gssp_tiqr_remote_ssourl%
                certificate: %gssp_tiqr_remote_certificate%
