imports:
    - { resource: samlstepupproviders_parameters.yml }

surfnet_stepup_gateway_saml_stepup_provider:
    allowed_sps: %gssp_allowed_sps%
    routes:
        sso: gssp_verify
        consume_assertion: gssp_consume_assertion
        metadata: gssp_saml_metadata
    providers:
        tiqr:
            enabled: %gssp_tiqr_enabled%
            hosted:
                service_provider:
                    public_key: %gssp_tiqr_sp_publickey%
                    private_key: %gssp_tiqr_sp_privatekey%
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: %gssp_tiqr_idp_publickey%
                    private_key: %gssp_tiqr_idp_privatekey%
                metadata:
                    public_key: %gssp_tiqr_metadata_publickey%
                    private_key: %gssp_tiqr_metadata_privatekey%
            remote:
                entity_id: %gssp_tiqr_remote_entity_id%
                sso_url: %gssp_tiqr_remote_sso_url%
                certificate: %gssp_tiqr_remote_certificate%
