# Use this service definition file to override services in the test environment. For example to mock certain services

parameters:
  saml_metadata_publickey: /var/www/ci/certificates/sp.crt
  saml_metadata_privatekey: /var/www/ci/certificates/sp.pem
  saml_sp_publickey: /var/www/ci/certificates/sp.crt
  saml_sp_privatekey: /var/www/ci/certificates/sp.pem
  saml_idp_publickey: /var/www/ci/certificates/idp.crt
  saml_idp_privatekey: /var/www/ci/certificates/idp.key

services:
  _defaults:
    autowire: true
    autoconfigure: true

  surfnet_gateway_api.service.yubikey:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\YubikeyService

  gateway.service.gateway_api_sms:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\SmsService

  surfnet_stepup.service.challenge_handler:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\SessionSmsVerificationStateHandler

  Surfnet\StepupGateway\Behat\MinkContext:
    class: Surfnet\StepupGateway\Behat\MinkContext

#  todo: inject dbal connection
  Surfnet\StepupGateway\Behat\Repository\Connection:
    class: Surfnet\StepupGateway\Behat\Repository\Connection
    arguments:
      - 'gateway'
      - 'gateway'
      - 'gateway'
      - 'db.stepup.example.com'

  Surfnet\StepupGateway\Behat\Service\FixtureService:
    class: Surfnet\StepupGateway\Behat\Service\FixtureService

  Surfnet\StepupGateway\Behat\Controller\ServiceProviderController:
    class: Surfnet\StepupGateway\Behat\Controller\ServiceProviderController