# Use this service definition file to override services in the test environment. For example to mock certain services

parameters:
  app_name: 'Stepup Gateway'
  trusted_proxies:
    - 127.0.0.1
  use_assetic_controller: true
  database_driver: pdo_mysql
  database_host: db.stepup.example.com
  database_port: null
  saml_metadata_publickey: /var/www/ci/certificates/sp.crt
  saml_metadata_privatekey: /var/www/ci/certificates/sp.pem
  saml_sp_publickey: /var/www/ci/certificates/sp.crt
  saml_sp_privatekey: /var/www/ci/certificates/sp.pem
  saml_idp_publickey: /var/www/ci/certificates/idp.crt
  saml_idp_privatekey: /var/www/ci/certificates/idp.key
  selfservice_api_password: secret
  registration_authority_api_password: secret
  sms_otp_expiry_interval: 900
  saml_remote_idp_entity_id: 'https://gateway.stepup.example.com/test/authentication/metadata'
  saml_remote_idp_sso_url: 'https://gateway.stepup.example.com/test/authentication/sso'
  saml_remote_idp_certificate: MIIDuDCCAqCgAwIBAgIJAPdqJ9JQKN6vMA0GCSqGSIb3DQEBBQUAMEYxDzANBgNVBAMTBkVuZ2luZTERMA8GA1UECxMIU2VydmljZXMxEzARBgNVBAoTCk9wZW5Db25leHQxCzAJBgNVBAYTAk5MMB4XDTE1MDQwMjE0MDE1NFoXDTI1MDQwMTE0MDE1NFowRjEPMA0GA1UEAxMGRW5naW5lMREwDwYDVQQLEwhTZXJ2aWNlczETMBEGA1UEChMKT3BlbkNvbmV4dDELMAkGA1UEBhMCTkwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCeVodghQwFR0pItxGaJ3LXHA+ZLy1w/TMaGDcJaszAZRWRkL/6djwbabR7TB45QN6dfKOFGzobQxG1Oksky3gz4Pki1BSzi/DwsjWCw+Yi40cYpYeg/XM0tvHKVorlsx/7Thm5WuC7rwytujr/lV7f6lavf/ApnLHnOORU2h0ZWctJiestapMaC5mc40msruWWp04axmrYICmTmGhEy7w0qO4/HLKjXtWbJh71GWtJeLzG5Hj04X44wI+D9PUJs9U3SYh9SCFZwq0v+oYeqajiX0JPzB+8aVOPmOOM5WqoT8OCddOM/TlsL/0PcxByGHsgJuWbWMI1PKlK3omR764PAgMBAAGjgagwgaUwHQYDVR0OBBYEFLowmsUCD2CrHU0lich1DMkNppmLMHYGA1UdIwRvMG2AFLowmsUCD2CrHU0lich1DMkNppmLoUqkSDBGMQ8wDQYDVQQDEwZFbmdpbmUxETAPBgNVBAsTCFNlcnZpY2VzMRMwEQYDVQQKEwpPcGVuQ29uZXh0MQswCQYDVQQGEwJOTIIJAPdqJ9JQKN6vMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAIF9tGG1C9HOSTQJA5qL13y5Ad8G57bJjBfTjp/dw308zwagsdTeFQIgsP4tdQqPMwYmBImcTx6vUNdiwlIol7TBCPGuqQAHD0lgTkChCzWezobIPxjitlkTUZGHqn4Kpq+mFelX9x4BElmxdLj0RQV3c3BhoW0VvJvBkqVKWkZ0HcUTQMlMrQEOq6D32jGh0LPCQN7Ke6ir0Ix5knb7oegND49fbLSxpdo5vSuxQd+Zn6nI1/VLWtWpdeHMKhiw2+/ArR9YM3cY8UwFQOj9Y6wI6gPCGh/q1qv2HnngmnPrNzZik8XucGcf1Wm2zE4UIVYKW31T52mqRVDKRk8F3Eo=
  gateway_loa_loa1: 'http://stepup.example.com/assurance/level1'
  gateway_loa_loa2: 'http://stepup.example.com/assurance/level2'
  gateway_loa_loa3: 'http://stepup.example.com/assurance/level3'
  second_factor_only_loa_loa2: 'http://stepup.example.com/assurance/sfo-level2'
  second_factor_only_loa_loa3: 'http://stepup.example.com/assurance/sfo-level3'
  locales:
    - nl_NL
    - en_GB
  second_factor_only: true
  support_url:
    en_GB: 'https://support.example.org'
    nl_NL: 'https://support.example.org'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  surfnet_gateway_api.service.yubikey:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\YubikeyService

  gateway.service.gateway_api_sms:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\SmsService

  surfnet_stepup.service.challenge_handler:
    class: Surfnet\StepupGateway\ApiBundle\Tests\TestDouble\Service\SessionSmsVerificationStateHandler

  Surfnet\StepupGateway\Behat\MinkContext:
    class: Surfnet\StepupGateway\Behat\MinkContext

#  todo: inject dbal connection
  Surfnet\StepupGateway\Behat\Repository\Connection:
    class: Surfnet\StepupGateway\Behat\Repository\Connection
    arguments:
      - 'gateway'
      - 'gateway'
      - 'gateway'
      - 'db.stepup.example.com'

  Surfnet\StepupGateway\Behat\Service\FixtureService:
    class: Surfnet\StepupGateway\Behat\Service\FixtureService

  Surfnet\StepupGateway\Behat\Controller\ServiceProviderController:
    class: Surfnet\StepupGateway\Behat\Controller\ServiceProviderController

  Surfnet\StepupGateway\Behat\Controller\IdentityProviderController:
    class: Surfnet\StepupGateway\Behat\Controller\IdentityProviderController
