monolog:
  channels: [authentication]
  handlers:
    prod-signaler:
      type: fingers_crossed
      action_level: ERROR
      passthru_level: DEBUG
      handler: main_syslog
      bubble: true
      channels: ["!authentication"] # the auth channel is logged by the next handler
    main_syslog:
      type: stream
      path: "php://stderr"
      formatter: surfnet_stepup.monolog.json_formatter
    authenthentication_syslog:
      type: stream
      path: "php://stderr"
      channels: [authentication]
      formatter: gateway.monolog.gelf_to_string_formatter
    main_logfile:
      type: stream
      handler: logfile
      level: NOTICE
      path: "%kernel.logs_dir%/dev.log"
