gateway_saml_metadata:
    path:     /authentication/metadata
    methods:  [GET]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Gateway:metadata}

gateway_serviceprovider_consume_assertion:
    path:     /authentication/consume-assertion
    methods:  [POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Gateway:consumeAssertion }

gateway_identityprovider_sso:
    path:     /authentication/single-sign-on
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Gateway:sso }

gateway_identityprovider_sso_proxy:
    path:     /authentication/single-sign-on/{idpKey}
    methods:  [POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Gateway:proxySso }


gateway_verify_second_factor_yubikey:
    path:     /verify-second-factor/yubikey
    methods:  [GET,POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Yubikey:verifyYubikeySecondFactor }


gateway_verify_second_factor_sms:
    path:     /verify-second-factor/sms/send-challenge
    methods:  [GET,POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Sms:verifySmsSecondFactor }

gateway_verify_second_factor_sms_verify_challenge:
    path:     /verify-second-factor/sms/verify-challenge
    methods:  [GET,POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Sms:verifySmsSecondFactorChallenge }


gateway_verify_second_factor_gssf:
    path:     /verify-second-factor/gssf
    methods:  [GET]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:Gssf:verifyGssf }


gateway_verify_second_factor_u2f:
    path:     /verify-second-factor/u2f/authenticate
    methods:  [GET]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:U2f:initiateU2fAuthentication }

gateway_verify_second_factor_u2f_verify_authentication:
    path:     /verify-second-factor/u2f/authenticate
    methods:  [POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:U2f:verifyU2fAuthentication }

gateway_verify_second_factor_u2f_cancel_authentication:
    path:     /verify-second-factor/u2f/cancel
    methods:  [POST]
    defaults: { _controller: SurfnetStepupGatewayGatewayBundle:U2f:cancelU2fAuthentication }
