services:
    saml.entity_repository:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SamlEntityService
        arguments:
            - @gateway.repository.saml_entity

    gateway.service.loa_resolution:
        class: Surfnet\StepupGateway\GatewayBundle\Service\LoaResolutionService

    gateway.proxy.state_handler:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\Proxy\ProxyStateHandler
        arguments:
            - @session

    gateway.proxy.response_builder:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\ResponseBuilder

    gateway.proxy.response_context:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\ResponseContext
        arguments:
            - @surfnet_saml.hosted.identity_provider
            - @saml.entity_repository
            - @gateway.proxy.state_handler

    gateway.service.response_proxy:
        class: Surfnet\StepupGateway\GatewayBundle\Service\ProxyResponseService
        arguments:
            - @surfnet_saml.hosted.identity_provider
            - @gateway.proxy.state_handler
            - @gateway.service.assertion_signing
            - @surfnet_saml.saml.attribute_dictionary
            - @saml.attribute.eduPersonTargetedID

    gateway.service.assertion_signing:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\AssertionSigningService
        arguments:
            - @surfnet_saml.hosted.identity_provider

    gateway.service.stepup_authentication:
        class: Surfnet\StepupGateway\GatewayBundle\Service\StepUpAuthenticationService
        arguments:
            - @gateway.service.loa_resolution
