services:
    saml.entity_repository:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SamlEntityService
        arguments:
            - @gateway.repository.saml_entity

    gateway.service.loa_resolution:
        class: Surfnet\StepupGateway\GatewayBundle\Service\LoaResolutionService

    gateway.proxy.state_handler:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\Proxy\ProxyStateHandler
        arguments:
            - @session

    gateway.proxy.response_builder:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\ResponseBuilder

    gateway.proxy.response_context:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\ResponseContext
        arguments:
            - @surfnet_saml.hosted.identity_provider
            - @saml.entity_repository
            - @gateway.proxy.state_handler

    gateway.service.response_proxy:
        class: Surfnet\StepupGateway\GatewayBundle\Service\ProxyResponseService
        arguments:
            - @surfnet_saml.hosted.identity_provider
            - @gateway.proxy.state_handler
            - @gateway.service.assertion_signing
            - @surfnet_saml.saml.attribute_dictionary
            - @saml.attribute.eduPersonTargetedID

    gateway.service.assertion_signing:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\AssertionSigningService
        arguments:
            - @surfnet_saml.hosted.identity_provider

    gateway.service.stepup_authentication:
        class: Surfnet\StepupGateway\GatewayBundle\Service\StepUpAuthenticationService
        arguments:
            - @gateway.service.loa_resolution
            - @saml.entity_repository
            - @gateway.repository.second_factor
            - @surfnet_gateway_api.service.yubikey
            - @gateway.service.sms_second_factor

    gateway.service.sms_second_factor:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SmsSecondFactorService
        arguments:
            - @surfnet_gateway_api.service.sms
            - @gateway.sms.challenge_store
            - @translator
            - 'SURFnet'

    gateway.sms.challenge_store:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SmsSecondFactor\SessionChallengeStore
        arguments:
            - @session
            - 'Surfnet/Gateway/SecondFactor/Sms:challenge'

    # Forms
    gateway.form.type.anchor:
        class: Surfnet\StepupGateway\GatewayBundle\Form\Type\AnchorType
        tags: [{ name: form.type, alias: anchor }]

    gateway.form.verify_yubikey:
        class: Surfnet\StepupGateway\GatewayBundle\Form\Type\VerifyYubikeyOtpType
        tags: [{ name: form.type, alias: gateway_verify_yubikey_otp }]

    gateway.form.send_sms_challenge:
        class: Surfnet\StepupGateway\GatewayBundle\Form\Type\SendSmsChallengeType
        tags: [{ name: form.type, alias: gateway_send_sms_challenge }]

    gateway.form.verify_sms_challenge:
        class: Surfnet\StepupGateway\GatewayBundle\Form\Type\VerifySmsChallengeType
        tags: [{ name: form.type, alias: gateway_verify_sms_challenge }]
