services:
    saml.entity_repository:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SamlEntityService
        arguments:
            - @gateway.repository.saml_entity

    gateway.service.loa_resolution:
        class: Surfnet\StepupGateway\GatewayBundle\Service\LoaResolutionService

    gateway.proxy.state_handler:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\Proxy\ProxyStateHandler
        arguments:
            - @session
