include: 
  - ../../devconf/stepup/docker-compose.yml

services:

    selenium:
       image: selenium/standalone-chrome:latest
       container_name: gateway-selenium
       environment:
           START_XVFB: "false"
       volumes:
            - /dev/shm:/dev/shm
       networks:
         openconextdev:
           aliases:
             - selenium.dev.openconext.local
