include: 
  - ../../devconf/stepup/docker-compose.yml

services:

    selenium:
       image: zenika/alpine-chrome:latest
       container_name: gateway-selenium
       command: ["--no-sandbox", "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--ignore-certificate-errors", "--disable-dev-shm-usage"]
       volumes:
            - /dev/shm:/dev/shm
       networks:
         openconextdev:
           aliases:
             - selenium.dev.openconext.local
             - chrome.dev.openconext.local
