version: '3.6'

services:

    ssp.stepup.example.com:
        image: ghcr.io/openconext/openconext-containers/openconext-ssp-debug-sp:latest
        volumes:
            - ../certificates/sp.crt:/app/cert/sp.crt
            - ../certificates/sp.key:/app/cert/sp.key
            - ../certificates/idp.crt:/app/cert/idp.crt
            - ../certificates/idp.key:/app/cert/idp.key
            - ../certificates/ssp.crt:/app/cert/ssp.crt
            - ../certificates/ssp.key:/app/cert/ssp.key
        container_name: gateway-ssp

    db.stepup.example.com:
        image: mariadb:10.6
        restart: always
        container_name: gateway-db
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "gateway"
            MYSQL_USER: "gateway"
            MYSQL_PASSWORD: "gateway"
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - gateway-mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 20

    gateway.stepup.example.com:
        image: ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
        container_name: gateway
        volumes:
             - ../../:/var/www/html/
             - ../config/appconf.conf:/etc/apache2/sites-enabled/appconf.conf
             - ../certificates/idp.crt:/etc/apache2/certs/gateway.stepup.example.com.crt
             - ../certificates/idp.key:/etc/apache2/certs/gateway.stepup.example.com.key
        environment:
            APP_ENV: test
        ports:
            - 443:443
        depends_on:
            db.stepup.example.com:
                condition: service_healthy

    selenium.stepup.example.com:
        image: selenium/standalone-chrome:latest
        container_name: gateway-selenium
        environment:
            START_XVFB: "false"
        volumes:
            - /dev/shm:/dev/shm

volumes:
    gateway-mysql-data:
