version: '2.2'

services:
    gateway.stepup.example.com:
        image: nginx:latest
        container_name: gateway-nginx
        volumes:
            -  ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../public:/var/www/public
            - ../certificates/idp.crt:/etc/nginx/certs/gateway.stepup.example.com.crt
            - ../certificates/idp.key:/etc/nginx/certs/gateway.stepup.example.com.key
        environment:
            APP_ENV: test
        ports:
            - 443:443
        depends_on:
            - php-fpm.stepup.example.com

    db.stepup.example.com:
        image: mariadb:10.2
        restart: always
        container_name: gateway-db
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "gateway"
            MYSQL_USER: "gateway"
            MYSQL_PASSWORD: "gateway"
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - gateway-mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 20

    php-fpm.stepup.example.com:
        build:
            context: ../
            dockerfile: docker/php-fpm/Dockerfile
        container_name: gateway-phpfpm
        volumes:
            - ../../:/var/www
        environment:
            APP_ENV: test
            PHP_IDE_CONFIG: "serverName=gateway.stepup.example.com"
            XDEBUG_CONFIG: "remote_enable=1 remote_connect_back=1 remote_port=9001 idekey=PHPSTORM"
        user: '${UID}:${GID}'
        depends_on:
            db.stepup.example.com:
                condition: service_healthy

    selenium.stepup.example.com:
        image: selenium/standalone-chrome:2.53.1
        container_name: gateway-selenium
        user: '${UID}:${GID}'
        environment:
            START_XVFB: "false"
        volumes:
            - /dev/shm:/dev/shm

volumes:
    gateway-mysql-data:
