imports:
    - { resource: samlstepupproviders_parameters.yaml }

surfnet_stepup_gateway_saml_stepup_provider:
    allowed_sps: "%gssp_allowed_sps%"
    ra_vetting_procedure_sp_metadata_url_regex: "%gssp_ra_vetting_procedure_sp_metadata_url_regex%"
    routes:
        sso: gssp_verify
        consume_assertion: gssp_consume_assertion
        metadata: gssp_saml_metadata
    providers:
        tiqr:
            enabled: true
            hosted:
                service_provider:
                    public_key: "%gssp_tiqr_sp_publickey%"
                    private_key: "%gssp_tiqr_sp_privatekey%"
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: "%gssp_tiqr_idp_publickey%"
                    private_key: "%gssp_tiqr_idp_privatekey%"
                metadata:
                    public_key: "%gssp_tiqr_metadata_publickey%"
                    private_key: "%gssp_tiqr_metadata_privatekey%"
            remote:
                entity_id: "%gssp_tiqr_remote_entity_id%"
                sso_url: "%gssp_tiqr_remote_sso_url%"
                certificate: "%gssp_tiqr_remote_certificate%"
            view_config:
                logo: "%gssp_tiqr_logo%"
                title: "%gssp_tiqr_title%"
        webauthn:
            enabled: true
            hosted:
                service_provider:
                    public_key: "%gssp_webauthn_sp_publickey%"
                    private_key: "%gssp_webauthn_sp_privatekey%"
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: "%gssp_webauthn_idp_publickey%"
                    private_key: "%gssp_webauthn_idp_privatekey%"
                metadata:
                    public_key: "%gssp_webauthn_metadata_publickey%"
                    private_key: "%gssp_webauthn_metadata_privatekey%"
            remote:
                entity_id: "%gssp_webauthn_remote_entity_id%"
                sso_url: "%gssp_webauthn_remote_sso_url%"
                certificate: "%gssp_webauthn_remote_certificate%"
            view_config:
                logo: "%gssp_webauthn_logo%"
                title: "%gssp_webauthn_title%"
        azuremfa:
            enabled: true
            hosted:
                service_provider:
                    public_key: "%gssp_azuremfa_sp_publickey%"
                    private_key: "%gssp_azuremfa_sp_privatekey%"
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: "%gssp_azuremfa_idp_publickey%"
                    private_key: "%gssp_azuremfa_idp_privatekey%"
                metadata:
                    public_key: "%gssp_azuremfa_metadata_publickey%"
                    private_key: "%gssp_azuremfa_metadata_privatekey%"
            remote:
                entity_id: "%gssp_azuremfa_remote_entity_id%"
                sso_url: "%gssp_azuremfa_remote_sso_url%"
                certificate: "%gssp_azuremfa_remote_certificate%"
            view_config:
                logo: "%gssp_azuremfa_logo%"
                title: "%gssp_azuremfa_title%"
        demo_gssp:
            enabled: true
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_sp_publickey%"
                    private_key: "%gssp_demo_gssp_sp_privatekey%"
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: "%gssp_demo_gssp_idp_publickey%"
                    private_key: "%gssp_demo_gssp_idp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_remote_sso_url%"
                certificate: "%gssp_demo_gssp_remote_certificate%"
            view_config:
                logo: "%gssp_demo_gssp_logo%"
                title: "%gssp_demo_gssp_title%"
        demo_gssp_2:
            enabled: true
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_2_sp_publickey%"
                    private_key: "%gssp_demo_gssp_2_sp_privatekey%"
                identity_provider:
                    service_provider_repository: saml.entity_repository
                    public_key: "%gssp_demo_gssp_2_idp_publickey%"
                    private_key: "%gssp_demo_gssp_2_idp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_2_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_2_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_2_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_2_remote_sso_url%"
                certificate: "%gssp_demo_gssp_2_remote_certificate%"
            view_config:
                logo: "%gssp_demo_gssp_2_logo%"
                title: "%gssp_demo_gssp_2_title%"
