gssp_saml_metadata:
    path:     /gssp/{provider}/metadata
    methods:  [GET]
    defaults: { _controller: SurfnetStepupGatewaySamlStepupProviderBundle:SamlProxy:metadata}

gssp_consume_assertion:
    path:     /gssp/{provider}/consume-assertion
    methods:  [POST]
    defaults: { _controller: SurfnetStepupGatewaySamlStepupProviderBundle:SamlProxy:consumeAssertion }

gssp_verify:
    path:     /gssp/{provider}/single-sign-on
    methods:  [GET]
    defaults: { _controller: SurfnetStepupGatewaySamlStepupProviderBundle:SamlProxy:singleSignOn }
