services:
    gssp.provider_repository:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ProviderRepository

    gssp.connected_service_providers:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ConnectedServiceProviders
        arguments:
            - @saml.entity_repository
            - []

    gssp.session:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['gssp']

    gssp.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__gssp__'
            - '/'
        calls:
            - [setName, ['gssp']]

    gssp.service.gssp.login:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\LoginService
        arguments:
            - @surfnet_saml.logger
            - @surfnet_saml.http.redirect_binding
            - @gssp.connected_service_providers

    gssp.service.gssp.second_factor_verification:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\SecondFactorVerificationService
        arguments:
            - @surfnet_saml.logger
            - @gateway.proxy.response_context

    gssp.service.gssp.consume_assertion:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\ConsumeAssertionService
        arguments:
            - @logger
            - @surfnet_saml.logger
            - @surfnet_saml.http.post_binding
            - @gssp.connected_service_providers
