services:
    # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    gssp.provider_repository:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ProviderRepository
    Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ProviderRepository:
        alias: gssp.provider_repository

    gssp.allowed_sps:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\AllowedServiceProviders
        arguments:
            - []

    gssp.connected_service_providers:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ConnectedServiceProviders
        arguments:
            - "@saml.entity_repository"
            - "@gssp.allowed_sps"
    Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\ConnectedServiceProviders:
        alias: gssp.connected_service_providers

#    gssp.session:
#        class: Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
#        factory: ['@request_stack', 'getBag']
#        arguments: ['gssp']

    Surfnet\StepupGateway\SamlStepupProviderBundle\Provider\MetadataFactoryCollection:
    Surfnet\StepupGateway\SamlStepupProviderBundle\Saml\ProxyResponseFactoryCollection:

    gssp.session.attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
        arguments:
            - '__gssp__'
        calls:
            - [setName, ['gssp']]

    gssp.service.gssp.login:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\LoginService
        arguments:
            - "@surfnet_saml.logger"
            - "@surfnet_saml.http.redirect_binding"
            - "@gssp.connected_service_providers"
    Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\LoginService:
        alias: gssp.service.gssp.login

    gssp.service.gssp.second_factor_verification:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\SecondFactorVerificationService
        arguments:
            - "@surfnet_saml.logger"
            - "@gateway.proxy.response_context"
            - "@second_factor_only.response_context"
    Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\SecondFactorVerificationService:
        alias: gssp.service.gssp.second_factor_verification

    gssp.service.gssp.consume_assertion:
        class: Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\ConsumeAssertionService
        arguments:
            - "@logger"
            - "@surfnet_saml.logger"
            - "@surfnet_saml.http.post_binding"
            - "@gssp.connected_service_providers"
    Surfnet\StepupGateway\SamlStepupProviderBundle\Service\Gateway\ConsumeAssertionService:
        alias: gssp.service.gssp.consume_assertion
