FROM ghcr.io/openconext/openconext-basecontainers/php72-apache2-node14-composer2:latest

RUN rm -rf /etc/apache2/sites-enabled/*
COPY ./docker/conf/gateway-apache2.conf /etc/apache2/sites-enabled/gateway.conf
EXPOSE 80

# Set the default workdir
WORKDIR /var/www/html

ENTRYPOINT ["apache2-foreground"]
