gateway_test_consume_assertion:
  path:     /test/authentication/consume-assertion
  methods:  [POST]
  defaults: { _controller: Surfnet\StepupGateway\Behat\Controller\ServiceProviderController::acsAction }

gateway_test_remote_idp_sso:
  path:     /test/authentication/idp/sso
  methods:  [GET,POST]
  defaults: { _controller: Surfnet\StepupGateway\Behat\Controller\IdentityProviderController::ssoAction }

