services:
    surfnet_stepup.json_convertible_param_converter:
        class: Surfnet\StepupBundle\Request\JsonConvertibleParamConverter
        arguments:
            - @validator
        tags:
            - { name: request.param_converter, priority: -1, converter: surfnet_stepup.json_convertible }

    surfnet_stepup.listener.bad_json_request_exception_listener:
        class: Surfnet\StepupBundle\EventListener\BadJsonRequestExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    surfnet_stepup.request.request_id:
        class: Surfnet\StepupBundle\Request\RequestId
        arguments:
            - @surfnet_stepup.request.request_id_generator

    surfnet_stepup.request.request_id_generator:
        public: false
        class: Surfnet\StepupBundle\Request\RandomRequestIdGenerator

    surfnet_stepup.listener.request_id_request_listener:
        public: false
        class: Surfnet\StepupBundle\EventListener\RequestIdRequestListener
        arguments:
            - %request_id.header%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
