services:
    second_factor_only.configuration.hosted_entities:
        public: false
        class: Surfnet\SamlBundle\Entity\HostedEntities
        arguments:
            - @router
            - @request_stack
            - null
            - enabled: true
              entity_id_route: 'gateway_second_factor_only_metadata'
              sso_route: 'gateway_second_factor_only_identityprovider_sso'
              public_key: '%saml_idp_publickey%'
              private_key: '%saml_idp_privatekey%'

    second_factor_only.hosted.identity_provider:
        public: false
        class: Surfnet\SamlBundle\Entity\IdentityProvider
        factory: ['@second_factor_only.configuration.hosted_entities', getIdentityProvider]

    second_factor_only.configuration.metadata:
        public: false
        class: Surfnet\SamlBundle\Metadata\MetadataConfiguration
        properties:
            entityIdRoute: 'gateway_second_factor_only_metadata'
            isSp: false
            isIdP: true
            ssoRoute: 'gateway_second_factor_only_identityprovider_sso'
            idpCertificate: '%saml_idp_publickey%'
            publicKey: '%saml_metadata_publickey%'
            privateKey: '%saml_metadata_privatekey%'

    second_factor_only.metadata_factory:
        class: Surfnet\SamlBundle\Metadata\MetadataFactory
        arguments:
            - @templating
            - @router
            - @surfnet_saml.signing_service
            - @second_factor_only.configuration.metadata

    second_factor_only.response_rendering:
        class: Surfnet\StepupGateway\GatewayBundle\Service\ResponseRenderingService
        arguments:
            - @gateway.proxy.response_builder
            - @templating

    second_factor_only.response_context:
        class: Surfnet\StepupGateway\GatewayBundle\Saml\ResponseContext
        arguments:
            - @second_factor_only.hosted.identity_provider
            - @second_factor_only.entity_service
            - @gateway.proxy.state_handler

    second_factor_only.saml_response_factory:
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Saml\ResponseFactory
        arguments:
            - @second_factor_only.hosted.identity_provider
            - @gateway.proxy.state_handler
            - @second_factor_only.assertion_signing

    second_factor_only.assertion_signing:
        public: false
        class: Surfnet\StepupGateway\GatewayBundle\Saml\AssertionSigningService
        arguments:
            - @second_factor_only.hosted.identity_provider

    second_factor_only.http.binding_factory:
        class: Surfnet\SamlBundle\Http\HttpBindingFactory
        arguments:
            - @second_factor_only.http.redirect_binding
            - @second_factor_only.http.post_binding

    second_factor_only.http.redirect_binding:
        class: Surfnet\SamlBundle\Http\RedirectBinding
        arguments:
            - @logger
            - @surfnet_saml.signing.signature_verifier
            - @second_factor_only.entity_service

    second_factor_only.http.post_binding:
        class: Surfnet\SamlBundle\Http\PostBinding
        arguments:
            - '@surfnet_saml.saml2.response_processor'
            - @logger
            - @surfnet_saml.signing.signature_verifier
            - @second_factor_only.entity_service

    second_factor_only.entity_service:
        class: Surfnet\StepupGateway\GatewayBundle\Service\SamlEntityService
        arguments:
            - @second_factor_only.repository.gateway_saml_entity

    second_factor_only.repository.gateway_saml_entity:
        public: false
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Entity\SecondFactorOnlySamlEntityRepositoryDecorator
        arguments:
            - @gateway.repository.saml_entity

    second_factor_only.validate_nameid:
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Service\SecondFactorOnlyNameIdValidationService
        arguments:
            - @logger
            - @second_factor_only.entity_service

    second_factor_only.loa_resolution:
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Service\LoaResolutionService
        arguments:
            - @logger
            - @second_factor_only.loa_alias_lookup
            - @surfnet_stepup.service.loa_resolution

    second_factor_only.loa_alias_lookup:
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Service\LoaAliasLookupService
        arguments:
            - [] # See SurfnetStepupGatewaySecondFactorOnlyExtension::replaceLoaAliasConfig

    second_factor_only.adfs.state_handler:
        public: false
        arguments:
            - @session

        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Adfs\StateHandler

    second_factor_only.adfs.request_helper:
        arguments:
            - @second_factor_only.adfs.state_handler
            - @logger
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Adfs\RequestHelper
    second_factor_only.adfs.response_helper:
        arguments:
            - @second_factor_only.adfs.state_handler
            - @logger
        class: Surfnet\StepupGateway\SecondFactorOnlyBundle\Adfs\ResponseHelper