openconext_monitor:
  resource: "@OpenConextMonitorBundle/src/Controller"
  type: attribute
  prefix: /

nelmio_security_report:
  path: /csp/report
  defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
  methods: [POST]
