imports:
  - { resource: 'openconext/samlstepupproviders_parameters.yaml' }
  - { resource: 'openconext/global_view_parameters.yaml' }
  - { resource: 'openconext/parameters.yaml' }

services:
    # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $ssoResponseContext: '@gateway.proxy.response_context'
      $sfoResponseContext: '@second_factor_only.response_context'

  Surfnet\StepupGateway\SecondFactorOnlyBundle\Controller\:
    resource: '../src/Surfnet/StepupGateway/SecondFactorOnlyBundle/Controller/*'
    tags: [ 'controller.service_arguments' ]

  Surfnet\StepupGateway\GatewayBundle\Controller\:
    resource: '../src/Surfnet/StepupGateway/GatewayBundle/Controller/*'
    tags: [ 'controller.service_arguments' ]

  Surfnet\StepupGateway\ApiBundle\Controller\:
    resource: '../src/Surfnet/StepupGateway/ApiBundle/Controller/*'
    tags: [ 'controller.service_arguments' ]

  Surfnet\StepupGateway\SamlStepupProviderBundle\Controller\:
    resource: '../src/Surfnet/StepupGateway/SamlStepupProviderBundle/Controller/*'
    tags: [ 'controller.service_arguments' ]

  surfnet_gateway_api.service.provider:
    class: Surfnet\StepupGateway\ApiBundle\Sms\SmsAdapterProvider
    arguments: [ "%sms_service%" ]

  Surfnet\StepupGateway\ApiBundle\Sms\SmsAdapterProvider:
    alias: surfnet_gateway_api.service.provider

  logger:
    alias: 'monolog.logger'
    public: true
