imports:
  - { resource: 'openconext/samlstepupproviders_parameters.yaml' }
  - { resource: 'openconext/global_view_parameters.yaml' }
  - { resource: 'openconext/parameters.yaml' }
  - { resource: 'openconext/samlstepupproviders.yaml' }

services:
  logger:
    alias: 'monolog.logger'
    public: true

  twig.extension.text: # Required by JMSTranslationBundle
    class: Twig_Extensions_Extension_Text
    tags: [{ name: twig.extension }]

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags: [{ name: twig.extension }]
