sms_send:
    path:      /send-sms
    defaults:  { _controller: SurfnetStepupGatewayApiBundle:Sms:send }
    methods:   [POST]
    condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"
