doctrine:
  dbal:
    default_connection: gateway
    connections:
      gateway:
        driver:   "%database_driver%"
        port:     "%database_port%"
        host:     localhost
        dbname:   gateway_test
        user:     root
        password: password
        charset:  UTF8
