imports:
  - { resource: ../../services_test.yaml }
framework:
  test: ~
  session:
    handler_id: null
    storage_factory_id: session.storage.factory.mock_file
  profiler: { only_exceptions: false }
  php_errors:
    log: false # prevents user deprecated warnings
