name: build-push-test-docker-image

on:
  push:
    branches: 
      - feature/create_docker_publish_action
  workflow_dispatch:

jobs:
  build-push-test-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build the app
        uses: openconext/build-and-publish-test-container/php72-node14@main
        with:
          dir_to_include: 'tests/'
          use_yarn: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the TEST image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.test
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/openconext/stepup-gateway/stepup-gateway:test
