name: tag-release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      COMPONENT_NAME: Stepup-Gateway
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: OpenConext/Stepup-Build
          ref: master
          fetch-depth: 0

      - name: Output the semver tag to the tag variable
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
      - name: Run release script
        run: ./stepup-build.sh ${COMPONENT_NAME} --tag ${{ steps.vars.outputs.tag }}
      
      - name: Grab the archive filename
        id: archive
        run: |
          echo "archive=$(find . -maxdepth 1 -name "$COMPONENT_NAME*.tar.bz2" -printf '%f\n')" >> $GITHUB_OUTPUT
          echo "shasum=$(find . -maxdepth 1 -name "$COMPONENT_NAME*.sha" -printf '%f\n')" >> $GITHUB_OUTPUT
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.archive.outputs.archive }}
            ${{ steps.archive.outputs.shasum }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          generate_release_notes: true
  
  after_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker container build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-push-docker-image.yml
